### PR TITLE
Use Bourbon instead of Compass

### PR DESCRIPTION
**Pull request by nc**
Still working on this, but I thought I'd push it up so you could have a look.

### CODE REVIEW

**Comment by kim3er** [comment]
What's the benefit of using Bourbon over Compass? I really like Compass.

**Comment by nc** [comment]
@kim3er it's compatible with libsass / node-sass which is 40x faster than the Ruby sass compiler. 

Compass is cool - but it's only being used very sparingly within Clank. The API / mixins are very similar.

**Comment by kim3er** [comment]
Interesting, I didn't know that. Will take a closer look at Bourbon.

**Comment by Wolfr** [comment]
Compass development (the mixins that is) seemingly has stagnated over the
years so I'm not opposed to this.

I'll check out the changes.

**Comment by Wolfr** [comment]
Looking at the code I am sort of opposed with adding the full Bourbon
library in as this will introduce a dependency I would need to update.

Is there a way to use bourbon without including it (so it reads the mixins
from a compass plugin)?

On first thought I guess not since libsass probably works directly on the
files and that's why it doesn't work with Compass which reads mixins from
the ruby gem (I haven't used libsass/node-sass yet).

(Small thing, please remove the .takana-ignore files ;))

**Comment by nc** [comment]
Yes. You can avoid having the bourbon files in the scss folder by using a Compass plugin like https://github.com/jedfoster/bourbon-compass

That means the project depends on Compass, Bourbon Compass and Bourbon.

Alternatively, if you use the raw Bourbon files which are update-able by running `gem install bourbon && bourbon update` the project would only depend on Bourbon and Sass (either Ruby Sass or libsass). Which was my original intent with this pull request - to ensure libsass compatibility.

**Comment by nc** [comment]
@Wolfr will remove them :)

**Comment by Wolfr** [comment]
Won't fix.

We are using Compass for now.

**Pull request closed without merging**
